name: 'Ruff Linting'
description: 'Lint Python code using ruff'

inputs:
  python_version:
    description: 'Python version to set up'
    required: true
    default: '3.x'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python_version }}

    - name: Install Ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff  # Install Ruff
      shell: bash  # Specify the shell to use

    - name: Run Ruff
      run: |
        ruff check .  # Run ruff on the repository
      shell: bash  # Specify the shell to use
